// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdekcwbdlnpdrttabkvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kZWtjd2JkbG5wZHJ0dGFia3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjgxNjQsImV4cCI6MjA3MTEwNDE2NH0.kppsE5-AN59k2CHIdHRrk6S_nCOkbmWDcJCLQ8540jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});